### PR TITLE
added 1_1 piControl-ext85yr

### PR DESCRIPTION
**Pull request by TonyB9000**
Please check that I did that right.

### CODE REVIEW

**Comment by sterlingbaldwin** [comment]
I assume that since it was a continuation of the previous run, that it will also not include the required input variables as the previous run, so adding

```
    except:
            - siu
            - siv
            - clcalipso
```

will be needed.

**Review by sterlingbaldwin — CHANGES_REQUESTED** [review]
add the `except` list with the required variables.

**Comment by TonyB9000** [comment]
Sorry - I feel compelled to narrate my exploration.  Some of this belongs in the page:

> https://github.com/E3SM-Project/esgfpub/tree/master/warehouse

(Is there a "dataset_spec README.md somewhere?)

The dataset_spec is divided into 3 major areas:  "tables", "time-series" and "project".  The "tables" and "time-series" are lists of variables, organized into categories, apparently _somewhat_ realm-based.  The "project" section is broadly divided into "CMIP6" and "E3SM".

Project CMIP6 is further divided into sub-categories named "C4MIP", "ScenarioMIP" and "CMIP" (What are these things?)  They encapsulate lists of variables, organized by model and ~experiment (like "1pctCO2") or some sort of super-experiment grouping (ssp585-bgc).  These experiment-like items include "start", "end", "ens" (ensembles) and then some "except"-ed variables.

In contrast, Project E3SM divides immediately by model (no sub-categories), and under model by experiment, and then with the familiar "start", "end", "ens" and then the "except"-ed variables.  Some experiments include a "**cmip_case**". 

One could surmise that a "cmip_case" refers in some fashion to entries in the previous "Project CMIP6" section.  Let us explore that supposition.  Using "1_1_ECA piControl-ext85yr" as an example, we see that the cmip_case reads

> CMIP6.CMIP.E3SM-Project.E3SM-1-1-ECA.piControl

This maps to Project CMIP6, subsection "CMIP".  But then dives directly into E3SM-<model> with no intervening "E3SM-Project" subsection.  In any case, under the "model" = "E3SM-1-1-ECA" we find experiments "piControl" and "historical", but no entry for experiment "piControl-ext85yr".  Moreover, the piControl experiment reads (start,end) as (1850,2100).

In an effort to retain a degree of parallelism, I surmise we want to split this E3SM-1-1-ECA.piControl into one for (1850,2014), and another (with the "-ext85yr" suffix) for (2015,2100).

Likewise, the "cmip_case" under Project E3SM would need to read

> CMIP6.CMIP.E3SM-Project.E3SM-1-1-ECA.piControl-ext85yr

For the latter case.

I take the above text to be my direct translation of "add the except list with the required variables".

**Comment by TonyB9000** [comment]
Needed the cmip_case for both 1_1 and 1_1_ECA.

**Review by sterlingbaldwin — APPROVED** [review]
Looking good.

**Pull request merged**
