### PR TITLE
corrected file to_move or to_link from source that is file or link (t…

### PR DESCRIPTION
**Pull request by TonyB9000**
…arget)

### CODE REVIEW

**Comment by TonyB9000** [comment]
My stripped down unit test was successful, all modes (file to make_link, file_to_move, link_to_make_link, and link_target_to_move.)

But I still need to track down the mapfile name confusion.  I've added prints here and there in mapfile_generate, but it is going to ba a hassle if I need to generate mapfiles over and over...

**Comment by TonyB9000** [comment]
Ack!  I looked at the version I'd thought I'd pushed yesterday, and it didn't seem to have the changes I thought I'd made.  (creates src_parent and dst_parent from src_path and dst_path.)  I pushed it again (on the "fix_move_to_publication" branch).

**Comment by TonyB9000** [comment]
Note that I swapped the "move files" and "move mapfile" so that the mapfile is moved first, allowing an "abort" there to prevent the files from being moved - which is MUCH harder to undo/reset.  But I thought I'd commented out that "return 1" in the middle, before doing the commit and push... :(

**Review by sterlingbaldwin — APPROVED** [review]
Looks good to me

**Pull request merged**
