### PR TITLE
Moves the status files all to a joint location

### LINKED ISSUE #48: Move status file to publication directories when data files are moved

### PR DESCRIPTION
**Pull request by sterlingbaldwin**
Adds command line options and warehouse config items to allow the user to select where to send the dataset status files.

Fixes #48 and #35

### CODE REVIEW

**Review by TonyB9000 — COMMENTED** [review]
You've made several changes.  The ones related to status file location look good for __init__.py and warehouse.py, and warehouse_config, and Listener.  For dataset, I still see

> if self.status is None:
>             self.status_path = Path(self.warehouse_path, '.status')

(I need to check what "warehouse_path" is, when both source and destination are pub-directories.)  But shouldn't this be Path(DEFAULT_STATUS_PATH, f"{self.dataset_id}.status")

**Comment by sterlingbaldwin** [comment]
Not sure why I even put that there, I think I was trying to catch a rare but possible case, but honestly the status path should just be a required argument for the Dataset object, which would solve the problem.

**Comment by TonyB9000** [comment]
> **"Makes the status_path into a mandatory argument for the dataset object"**

Not sure how this helps.  What was wrong with a default value (/p/user_pub?e3sm/staging/status)?  Are you trying to accommodate E3SM and CMIP6 together? (they could be in the same directory).

QUESTION 1" If I want re-publish dsid1 and dsid2 in a single "warehouse publish" command, where these are already in publication, should I issue:

- warehouse publish -d dsid1 dsid2 
- warehouse publish -d dsid1 dsid2 -w /p/user_pub/work
- warehouse publish -and_now_for_something_entirely_different

Or must I launch separate warehouse publish calls, one per dataset_id?

QUESTION 2:  (side question) If I want to pre-generate the mapfiles for a selected set of dataset_id (in warehouse or publication), how would I do that?  Will "auto" do that routinely?

**Comment by sterlingbaldwin** [comment]
`warehouse publish -d dsid1 dsid2 -w /p/user_pub/work` is the right choice here.

**Comment by TonyB9000** [comment]
Ok, I see.  It is as much trouble actually verifying the correctness of a pre-made mapfile at publication time as it is just generating the mapfile afresh.  If that is the case, perhaps we just keep it as a publication step.  Alternately, if the mod-date on the mapfile is later than the mod-dates on every datafile, the mapfile must be correct (unless someone deliberately tampers with the mapfile...)

Now, I must always add "--status-path /p/user_pub/e3sm/staging/status" to any/all warehouse ops?  Not sure what problem that solved.

**Comment by sterlingbaldwin** [comment]
No, it just adds it so that the Dataset object must be given some value. If the datasets are created by the warehouse, the value given will be equal to either the user supplied argument, or the default if they give no value. The reason I changed it was so that internally the dataset.status_path will never be set to `None` which is the reason I had the defensive code before.

**Comment by sterlingbaldwin** [comment]
I merged the postprocessing branch into this one.

**Comment by sterlingbaldwin** [comment]
Since this PR is getting big, I think its time that it gets merged. I think the rest of the postprocessing jobs can get implemented by themselves, the main postprocess driver code is done.

**Comment by sterlingbaldwin** [comment]
Since there have been no objections, Im going to merge.

**Pull request merged**
