### PR TITLE
split BGC piControl into original and 85 year extension sets, and add…

### PR DESCRIPTION
**Pull request by TonyB9000**
…ed Archive_Map to the warehouse resources

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
Hey Tony, Thank you for the PR. But before merging, you want to  have  Sterling to review the code changes and to get  an approval..

**Comment by TonyB9000** [comment]
OK thanks.  I overlooked the review button when it said “no conflicts”.

(I was surprised I found the page for the PR at all.)

____tony____

**Comment by TonyB9000** [comment]
BTW – Once Sterling has departed, I assume I will have to ask you to be the reviewer.  Or you and Tom, … or …?

(Is Tom following this git discussion?)

____tony____

From: Bartoletti, Tony
Sent: Monday, August 2, 2021 3:59 PM
To: E3SM-Project/esgfpub ***@***.***>; E3SM-Project/esgfpub ***@***.***>
Cc: State change ***@***.***>
Subject: RE: [E3SM-Project/esgfpub] split BGC piControl into original and 85 year extension sets, and add… (#58)

OK thanks.  I overlooked the review button when it said “no conflicts”.

(I was surprised I found the page for the PR at all.)

____tony____

**Comment by chengzhuzhang** [comment]
Feel free to add me. and we can tag tom when needed

**Comment by TonyB9000** [comment]
Ok - When it comes time for reviewers, I'll figure out how.  ;) )

**Pull request merged**
